name: Workflow A

on:
#  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for artifact availability
        run: |
          sleep 10

      - name: Log workflow run ID
        run: |
          echo "Workflow run ID: ${{ github.event.workflow_run.id }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Upload Artifacts
        run: |
          hostname > stuff.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./stuff.txt
