name: Workflow A

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Upload Artifacts
        run: |
          hostname > stuff.txt
          
          # Your build steps here
        # Example of uploading an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./stuff.txt

