name: Workflow B

on:
  workflow_run:
    workflows: ["Workflow A"]   # Reference the name of Workflow A
    types:
      - completed               # Trigger when Workflow A is completed
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: write
  pull-requests: write
  checks: write

jobs:
  use_it:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts from Workflow A
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use the artifact
        run: |
          cat stuff.txt
